config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :listings, only: [:index, :show]
  resources :messages, only: [:index, :create]
  resources :reservations do
    member do
      post '/cancel' => 'reservations#cancel'
      get '/expire' => 'reservations#expire'
    end
  end
  post '/webhooks/:source' => 'webhooks#create'

  namespace :host do
    resources :merchant_settings do
      collection do
        get :connect, to: 'merchant_settings#connect'
        get :connected, to: 'merchant_settings#connected'
      end
    end
    resources :listings do
      resources :photos, only: [:index, :create, :destroy]
      resources :rooms, only: [:index, :create, :destroy]
    end
    resources :reservations, only: [:show]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.id == 1
  end
  constraints resque_web_constraint do
    mount Resque::Server, at: '/jobs'
  end
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                :bigint           not null, primary key
#  host_id           :bigint           not null
#  title             :string           not null
#  about             :text
#  max_guests        :integer          default(1)
#  address_line1     :string
#  address_line2     :string
#  city              :string
#  state             :string
#  postal_code       :string
#  country           :string
#  lat               :decimal(10, 6)
#  lng               :decimal(10, 6)
#  status            :integer          default("draft")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  nightly_price     :integer
#  cleaning_fee      :integer
#  stripe_product_id :string
#
class Listing < ApplicationRecord
  validates :nightly_price, numericality: { greater_than: 0 }
  validates :cleaning_fee, numericality: { greater_than: 0 }

  validates :title, presence: true
  validates :max_guests, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
  belongs_to :host, class_name: 'User'
  enum status: {draft: 0, published: 1, archived: 2}
  has_many :rooms
  has_many :photos
  has_many :calendar_events
  has_many :reservations
  scope :published, -> { where(status: :published) }

  after_commit :maybe_create_stripe_product, on: [:create, :update]

  def maybe_create_stripe_product
    return if !stripe_product_id.blank?

    product = Stripe::Product.create(
      name: title,
      url: Rails.application.routes.url_helpers.url_for(self),
      metadata: {
        clearbnb_id: id,
      }
    )
    update(stripe_product_id: product.id)
  end

  def address
    "#{address_line1} #{address_line2} #{city} #{state}"
  end
end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)
    if @listing.save
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update(listing_update_params)
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end

  def index
    @listings = current_user.listings.all
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status: :archived)
    redirect_to host_listings_path
  end

  private

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country,
      :lat,
      :lng,
      :nightly_price,
      :cleaning_fee
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :status,
      :nightly_price,
      :cleaning_fee
    )
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @listings = pagy(Listing.published, items: 6)
  end

  def show
    @listing = Listing.published.find(params[:id])
  end
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
  include Pagy::Frontend
end

app/views/listings/index.html.erb
<h1 class="text-2xl mb-4 font-bold">Listings</h1>

<div class="mb-4">
  <%== pagy_nav(@pagy) %>
</div>

<div data-controller="listing-map" data-action="map-loaded@window->address#initGoogle" class="grid grid-cols-2 gap-4">
  <ul role="list" data-listing-map-target="listings" class="col-span-1 grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
    <% @listings.each do |listing| %>
    <li class="relative" data-lat="<%= listing.lat %>" data-title="<%= listing.title %>" data-lng="<%= listing.lng %>">
      <a href="<%= listing_path(listing) %>" class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden">
        <img src="https://images.unsplash.com/photo-1582053433976-25c00369fc93?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=512&q=80" alt="" class="object-cover pointer-events-none group-hover:opacity-75">
        <button type="button" class="absolute inset-0 focus:outline-none">
          <span class="sr-only">View details for <%= listing.title %></span>
        </button>
      </a>
      <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-events-none"><%= listing.title %></p>
      <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= listing.nightly_price %></p>
    </li>
    <% end %>
  </ul>
  <div data-listing-map-target="map" class="cal-span-1 ">
  </div>
</div>

<div class="mt-4">
  <%== pagy_nav(@pagy) %>
</div>

app/views/listings/show.html.erb
<h1 class="text-2xl font-bold mb-4"><%= @listing.title %></h1>

<div>
  Per night <%= number_to_currency(@listing.nightly_price / 100, precision: 0) %>
</div>
<div>
  Cleaning fee <%= number_to_currency(@listing.cleaning_fee / 100, precision: 0) %>
</div>


<%= link_to "Reserve", new_reservation_path(listing_id: @listing.id) %>

<%= @listing.city %>, <%= @listing.state %>

<p>
  <%= @listing.about %>
</p>

<p>
  <%= @listing.max_guests %>
</p>


<% if @listing.photos.exists? %>
  <% @listing.photos.each do |photo| %>
    <%= image_tag photo.photo.variant(resize_to_limit: [100, 100]) %>
  <% end %>
<% end %>

<ul>
  <% @listing.rooms.each do |room| %>
  <li><%= room.room_type %> beds: <%= room.beds.count %></li>
  <% end %>
</ul>


<div>
  <h4>Host</h4>
  <%= @listing.host.email %>
</div>